### ISSUE TITLE
Re-design

### ISSUE THREAD

**Issue by mashdots** [mashdots/pointypoker#5]
Maybe rethink the general layout

- Use Flexbox and Grid
- Use inspiration for dashboard-like layout, combined with a grid system
- Better color accessibility
- Polish UI and make more consistent
- dark / light mode

Layout Inspiration: [Akron Street](https://akronstreet.com/)

### Dashboard Inspiration

To be categorized:
- https://dribbble.com/shots/20228923-Web-Analytics-UI-Dashboard
- https://dribbble.com/shots/23969513-Financial-Web-App-animation
- https://dribbble.com/shots/22543517-Crypto-Web-Dashboard
- https://dribbble.com/shots/24188150-Sales-Dashboard-Design-Concept
- https://dribbble.com/shots/16469084-Crypto-Dashboard
- https://dribbble.com/shots/24125144-Arbitra-crypto-arbitrage-dashboard
- https://dribbble.com/shots/19700264-Finance-Dashboard-Design
- https://dribbble.com/shots/19883146-Air-Quality-App
- https://dribbble.com/shots/22541272-Spectra-CRM-dashboard

Selected:
- Base the "panel" that appears with the room controls on the main page for [this dashboard](https://dribbble.com/shots/23473991-Business-Management-Dashboard). Note how the tool bar appears to be part of the background and the rest of the page appears to be a separate module / component
- Base the title input area on the search bar for [this dashboard](https://dribbble.com/shots/24188150-Sales-Dashboard-Design-Concept).

## Tasks
- [x] Set up new theme system
- [x] Fix Sign-in page alignment
- [x] Migrate from higher-order component to a separate component that uses hooks for auth
- [x] Re-design new session page
- [x] Create new container that will have the room / session controls
    - [x] When the room is created or navigated to, have it slide up from the bottom to appear
    - [x] Populate the name (better stylized) to the right of the main logo
    - [x] Have an exit button inside the panel with an icon and an animated text that appears
- [x] Create a grid system to contain panels
- [x] Create a reusable panel component that follow a style guide
- [ ] Create a new title input that is dynamic
    - [ ] Have two states - input and display
    - [ ] Input lets you input text (duh)
    - [ ] auto-changes to display mode for people who did not create the ticket
    - [ ] Display mode will be either text or a hyperlink based on a provided url
    - [ ] When a new ticket is created, add a "created by" prop to the ticket with the user's ID
    - [ ] Have a switcher button that animates when invoked
- [ ] Migrate existing panels to new panel system. Refresh designs
- [ ] Update distribution to be a pie chart instead of bars (or maybe give options?)
- [ ] Add iconography
